/*
	CREATE DATABASE ACT01;
	GO
	USE ACT01;
	GO
*/
IF OBJECT_ID('SANCIONES') IS NOT NULL DROP TABLE SANCIONES;
GO
IF OBJECT_ID('CONDUCTOR') IS NOT NULL DROP TABLE CONDUCTOR;
GO
IF OBJECT_ID('MATRICULA') IS NOT NULL DROP TABLE MATRICULA;
GO
CREATE TABLE MATRICULA(
	ID INT IDENTITY(1,1),
	NUMERO VARCHAR(20) UNIQUE NOT NULL,
	FECHA_EXPEDICION DATE NOT NULL,
	VALIDA_HASTA DATE NOT NULL,
	ACTIVO BIT NOT NULL DEFAULT 1,

	CONSTRAINT PK_MATRICULA_01 PRIMARY KEY(ID)
);
GO
INSERT INTO MATRICULA(NUMERO, FECHA_EXPEDICION, VALIDA_HASTA, ACTIVO) VALUES('AES', '01-01-2000', '01-01-2010', 1);
GO
CREATE TABLE CONDUCTOR(
	ID INT IDENTITY(1,1),
	IDENTIFICACION VARCHAR(15) UNIQUE NOT NULL,
	NOMBRE VARCHAR(20) NOT NULL,
	APELLIDO VARCHAR(20) NOT NULL,
	DIRECCION VARCHAR(30),
	TELEFONO VARCHAR(15) UNIQUE NOT NULL,
	EMAIL VARCHAR(30) UNIQUE NOT NULL,
	FECHA_NACIMIENTO DATE,
	ACTIVO BIT NOT NULL DEFAULT 1

	CONSTRAINT FK_CONDUCTOR_01 PRIMARY KEY(ID),
	MATRICULA_ID INT UNIQUE FOREIGN KEY REFERENCES MATRICULA(ID)
	ON DELETE CASCADE
	ON UPDATE CASCADE
);
GO
INSERT INTO CONDUCTOR(IDENTIFICACION, NOMBRE, APELLIDO, DIRECCION, TELEFONO, EMAIL, FECHA_NACIMIENTO, ACTIVO, MATRICULA_ID)
VALUES('36342567', 'Dayana Carolina', 'Vanegas', 'El Bolívar', '3105487612', 'dvanegas@yahoo.com', '16-10-1986', 1, 1);

GO
CREATE TABLE SANCIONES(
	ID INT IDENTITY(1,1),
	FECHA_ACTUAL DATE DEFAULT GETDATE() NOT NULL,
	SANCION VARCHAR(100) NOT NULL,											
	OBSERVACION VARCHAR(MAX),
	VALOR DECIMAL(10,2) NOT NULL,
	
	CONSTRAINT FK_SANCIONES_01 PRIMARY KEY(ID),
	CONDUCTOR_ID INT FOREIGN KEY REFERENCES CONDUCTOR(ID)
	ON DELETE CASCADE
	ON UPDATE CASCADE
);